// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPizza struct {
	Price    string    `json:"price"`
	Toppings []*string `json:"toppings"`
}

type Pizza struct {
	ID       string    `json:"_id"`
	Price    string    `json:"price"`
	Toppings []*string `json:"toppings"`
}
